# -*- coding: utf-8 -*-
"""movie_exploratory_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvtCfqRmUu_faSAy95tHMukWb1KDpGK8
"""

#importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load datasets
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')



#merge datasets
data = pd.merge(ratings, movies, on= 'movieId')

data.head(5)

#Clean datasets
data['timestamp'] = pd.to_datetime(data['timestamp'], unit = 's')

#Top-Rated movies
top_rated = data.groupby('title')['rating'].mean().sort_values(ascending=False).head(10)

top_rated.head(5)

#Average rating by genre
data['genres'] = data['genres'].fillna('').str.split('|')
data_exploded = data.explode('genres')

avg_rating_genre = data_exploded.groupby('genres')['rating'].mean().sort_values(ascending = False)

print(avg_rating_genre)

# ratings trends over time
data['year'] = data['timestamp'].dt.year
ratings_trends = data.groupby('year')['rating'].mean()

print(ratings_trends)

# visualization
plt.figure(figsize = (10,5))
sns.barplot(x=top_rated.index, y=top_rated.values)
plt.title('Top 10 rated movies')
plt.xticks(rotation = 45)
plt.show()

plt.figure(figsize = (10,5))
sns.lineplot(x=ratings_trends.index, y=ratings_trends.values)
plt.title('Average Ratings Over Time')
plt.show()